# Generated by Django 4.1.6 on 2023-03-12 20:52

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_remove_student_turma_classe_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('numero_de_bi', models.CharField(blank=True, max_length=13)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('birth_date', models.DateField()),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('quarteirao', models.CharField(blank=True, max_length=100)),
                ('classe', models.ManyToManyField(blank=app2.models.Turma, to='app2.classe')),
                ('subjects', models.ManyToManyField(blank=True, to='app2.subjectmark')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
