# Generated by Django 4.1.6 on 2023-03-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_student_phone_number_teacher_phone_number_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
