# Generated by Django 4.1.6 on 2023-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_classe_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ('name',), 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
