# Generated by Django 4.1.6 on 2023-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_alter_classe_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
