# Generated by Django 4.1.6 on 2023-03-14 16:11

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_parent_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=app2.models.Turma, to='app2.parent'),
        ),
    ]
