# Generated by Django 4.1.6 on 2023-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_remove_parent_student_student_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
