# Generated by Django 4.1.6 on 2023-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_subjectname_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('subjects', models.ManyToManyField(to='app2.subjectmark')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'year')},
            },
        ),
    ]
