# Generated by Django 4.1.6 on 2023-03-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_alter_semester_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.classe'),
        ),
    ]
