# Generated by Django 4.1.6 on 2023-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0023_teacher_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='study_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
