# Generated by Django 4.1.6 on 2023-05-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0025_classenewmodel_semesternewmodel_testnewmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectnamenewmodel',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='subjectnamenewmodel',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subjectnamenewmodel',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='subjectnamenewmodel',
            name='turma',
        ),
        migrations.DeleteModel(
            name='ClasseNewModel',
        ),
        migrations.DeleteModel(
            name='SemesterNewModel',
        ),
        migrations.DeleteModel(
            name='SubjectNameNewModel',
        ),
        migrations.DeleteModel(
            name='TestNewModel',
        ),
        migrations.DeleteModel(
            name='TurmaNewModel',
        ),
    ]
