# Generated by Django 4.1.6 on 2023-05-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0029_classenewmodel_semesternewmodel_testnewmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectnewmodel',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='testnewmodel',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
    ]
