# Generated by Django 4.1.6 on 2023-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0030_alter_subjectnewmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesternewmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
