# Generated by Django 4.1.6 on 2023-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0032_alter_semesternewmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesternewmodel',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
