# Generated by Django 4.1.6 on 2023-05-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0033_alter_semesternewmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenewmodel',
            name='name',
            field=models.CharField(choices=[('8ª classe', '8ª Classe'), ('9ª classe', '9ª Classe'), ('10ª classe', '10ª Classe'), ('11ª classe', '11ª Classe'), ('12ª classe', '12ª Classe')], max_length=15),
        ),
    ]
