# Generated by Django 4.1.6 on 2023-05-31 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0036_alter_classenewmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectNameNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='subjectnewmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.subjectnamenewmodel'),
        ),
    ]
