# Generated by Django 4.1.6 on 2023-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0037_subjectnamenewmodel_alter_subjectnewmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectnamenewmodel',
            options={'verbose_name': 'Subject Name', 'verbose_name_plural': 'Subjects Name'},
        ),
        migrations.AlterField(
            model_name='subjectnewmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='app2.testnewmodel'),
        ),
    ]
