# Generated by Django 4.1.6 on 2023-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0041_studentnamenewmodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=2023, max_length=4, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentnamenewmodel',
            name='year',
        ),
        migrations.AddField(
            model_name='studentnamenewmodel',
            name='year',
            field=models.ManyToManyField(blank=True, to='app2.year'),
        ),
    ]
