# Generated by Django 4.1.6 on 2023-05-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0043_subjecttestsnewmodel_semestermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='app2.subjecttestsnewmodel'),
        ),
    ]
