# Generated by Django 4.1.6 on 2023-05-31 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0044_alter_semestermodel_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodel',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app2.year'),
        ),
    ]
