# Generated by Django 4.1.6 on 2023-06-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0046_alter_semestermodel_name_alter_semestermodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnamenewmodel',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='studentnamenewmodel',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentnamenewmodel',
            name='turma',
        ),
    ]
