# Generated by Django 4.1.6 on 2023-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0047_remove_studentnamenewmodel_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentNameNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.AlterModelOptions(
            name='semestermodel',
            options={'verbose_name': 'New Semester', 'verbose_name_plural': 'New Semester'},
        ),
        migrations.AddField(
            model_name='studentnamenewmodel',
            name='parents',
            field=models.ManyToManyField(blank=True, to='app2.parentnamenewmodel'),
        ),
    ]
