# Generated by Django 4.1.6 on 2023-06-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0048_parentnamenewmodel_alter_semestermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnamenewmodel',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
