# Generated by Django 4.1.6 on 2023-06-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0052_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=13)),
                ('receiver', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
