# Generated by Django 4.1.6 on 2023-06-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0053_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('sender',)},
        ),
    ]
