# Generated by Django 4.1.6 on 2023-06-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0054_alter_message_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
