# Generated by Django 4.1.6 on 2023-06-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0057_messageadmin_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageadmin',
            options={'ordering': ('sender',), 'verbose_name': 'Admin Message', 'verbose_name_plural': 'Admin Messages'},
        ),
    ]
