# Generated by Django 4.1.6 on 2023-06-11 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0058_alter_messageadmin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('class_time', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.semestermodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.studentnamenewmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.subjectnamenewmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.teachernamenewmodel')),
            ],
        ),
    ]
