# Generated by Django 4.1.6 on 2023-06-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0059_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_time',
            field=models.DateTimeField(),
        ),
    ]
