# Generated by Django 4.1.6 on 2023-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0060_alter_attendance_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
