# Generated by Django 4.1.6 on 2023-06-11 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0062_rename_messageadmin_studentmessageadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessageAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app2.parentnamenewmodel')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Parent Message',
                'verbose_name_plural': 'Admin Parent Messages',
                'ordering': ('sender',),
            },
        ),
    ]
