# Generated by Django 4.1.6 on 2023-06-11 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0063_teachermessageadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherMessageAdmin',
            new_name='ParentMessageAdmin',
        ),
        migrations.AlterModelOptions(
            name='studentmessageadmin',
            options={'ordering': ('sender',), 'verbose_name': 'Admin Student Message', 'verbose_name_plural': 'Admin Student Messages'},
        ),
    ]
