# Generated by Django 4.1.6 on 2023-06-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0065_admintoparentmessageadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintoparentmessageadmin',
            options={'ordering': ('sender',), 'verbose_name': 'Parent Admin Message', 'verbose_name_plural': 'Parent Admin Messages'},
        ),
    ]
