# Generated by Django 4.1.6 on 2023-06-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0067_alter_teachernamenewmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectnewmodel',
            name='classe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app2.classenewmodel'),
        ),
        migrations.AlterField(
            model_name='subjectnewmodel',
            name='semester',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app2.semesternewmodel'),
        ),
        migrations.AlterField(
            model_name='subjectnewmodel',
            name='turma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app2.turmanewmodel'),
        ),
    ]
