# Generated by Django 4.1.6 on 2023-06-14 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0069_rename_parentmessageadmin_parenttoaadminmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminToParentMessageAdmin',
            new_name='AdminToParentMessage',
        ),
    ]
