# Generated by Django 4.1.6 on 2023-06-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0071_admintoteachermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintoteachermessage',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app2.teachernamenewmodel'),
        ),
    ]
