# Generated by Django 4.1.6 on 2023-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0072_alter_admintoteachermessage_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentnamenewmodel',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
        migrations.AddField(
            model_name='semestermodel',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=25),
        ),
    ]
