# Generated by Django 4.1.6 on 2023-06-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0073_alter_studentnamenewmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentnamenewmodel',
            options={'ordering': ('first_name',), 'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
