# Generated by Django 4.1.6 on 2023-06-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0075_parenttoadminmessage_admintoparentsmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parenttoaadminmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='parenttoaadminmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='AdminToParentMessage',
        ),
        migrations.DeleteModel(
            name='ParentToAadminMessage',
        ),
    ]
