# Generated by Django 4.1.6 on 2023-06-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0076_remove_parenttoaadminmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenewmodel',
            name='name',
            field=models.CharField(choices=[('7ª classe', '7ª Classe'), ('8ª classe', '8ª Classe'), ('9ª classe', '9ª Classe'), ('10ª classe', '10ª Classe'), ('11ª classe', '11ª Classe'), ('12ª classe', '12ª Classe')], max_length=15, unique=True),
        ),
    ]
