# Generated by Django 4.1.6 on 2023-06-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0077_alter_classenewmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodel',
            name='active_semester',
            field=models.BooleanField(default=False),
        ),
    ]
