# Generated by Django 4.1.6 on 2023-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0079_subjecttimetable_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttimetable',
            name='class_time',
            field=models.TimeField(),
        ),
    ]
