# Generated by Django 4.1.6 on 2023-06-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0080_alter_subjecttimetable_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='year',
        ),
        migrations.DeleteModel(
            name='SubjectTimetable',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
