# Generated by Django 4.1.6 on 2023-06-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0081_remove_timetable_classe_remove_timetable_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.subjectnamenewmodel')),
            ],
            options={
                'verbose_name': 'Subject Timetable',
                'verbose_name_plural': 'Subject Timetable',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.classenewmodel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.semesternewmodel')),
                ('subject', models.ManyToManyField(blank=True, to='app2.subjecttimetable')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.turmanewmodel')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.year')),
            ],
        ),
    ]
