# Generated by Django 4.1.6 on 2023-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0082_subjecttimetable_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttimetable',
            name='class_day',
            field=models.CharField(choices=[('2ª Feira', '2ª Feira'), ('3ª Feira', '3ª Feira'), ('4ª Feira', '4ª Feira'), ('5ª Feira', '5ª Feira'), ('6ª Feira', '6ª Feira')], default='2ª Feira', max_length=10),
        ),
    ]
