# Generated by Django 4.1.6 on 2023-06-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0084_rename_subject_timetable_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='teachernamenewmodel',
            name='class_attendance',
            field=models.ManyToManyField(blank=True, to='app2.teacherclassattendance'),
        ),
    ]
