# Generated by Django 4.1.6 on 2023-06-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0085_teacherclassattendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachernamenewmodel',
            name='class_attendance',
        ),
        migrations.DeleteModel(
            name='TeacherClassAttendance',
        ),
    ]
