# Generated by Django 4.1.6 on 2023-06-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0086_remove_teachernamenewmodel_class_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.teachernamenewmodel')),
            ],
        ),
    ]
