# Generated by Django 4.1.6 on 2023-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0087_teacherclassattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassattendance',
            name='lecionou',
            field=models.BooleanField(default=False),
        ),
    ]
