# Generated by Django 4.1.6 on 2023-06-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0090_rename_attented_teacherclassattendance_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassattendance',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.classenewmodel'),
        ),
        migrations.AddField(
            model_name='teacherclassattendance',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.turmanewmodel'),
        ),
    ]
