# Generated by Django 4.1.6 on 2023-06-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0091_teacherclassattendance_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassattendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.subjectnamenewmodel'),
        ),
    ]
