# Generated by Django 4.1.6 on 2023-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0092_teacherclassattendance_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchoolAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='teachernamenewmodel',
            name='school_attended',
            field=models.ManyToManyField(blank=True, to='app2.teacherschoolattended'),
        ),
    ]
