# Generated by Django 4.1.6 on 2023-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0093_teacherschoolattended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschoolattended',
            name='degree',
            field=models.CharField(choices=[('Nivel Medio', 'Nivel Medio'), ('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Doutoramento', 'Doutoramento')], default='Licenciatura', max_length=50),
        ),
    ]
