# Generated by Django 4.1.6 on 2023-06-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0097_remove_subjecttestsnewmodel_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttestsnewmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='app2.testnewmodel'),
        ),
    ]
