# Generated by Django 4.1.6 on 2023-06-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0099_remove_subjecttestsnewmodel_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turmanewmodel',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.RemoveField(
            model_name='subjectnewmodel',
            name='tests',
        ),
        migrations.DeleteModel(
            name='TestNewModel',
        ),
    ]
