# Generated by Django 4.1.6 on 2023-06-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0100_alter_turmanewmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AlterModelOptions(
            name='turmanewmodel',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddField(
            model_name='subjectnewmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='app2.testnewmodel'),
        ),
        migrations.AddField(
            model_name='subjecttestsnewmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='app2.testnewmodel'),
        ),
    ]
