# Generated by Django 4.1.6 on 2023-06-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0101_testnewmodel_alter_turmanewmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentnamenewmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
