# Generated by Django 4.1.6 on 2023-06-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0107_teachernamenewmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='subjecttestsnewmodel',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='app2.studentattendance'),
        ),
    ]
