# Generated by Django 4.1.6 on 2023-06-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0108_studentattendance_subjecttestsnewmodel_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='class_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
