# Generated by Django 4.1.6 on 2023-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0109_alter_studentattendance_class_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'verbose_name': 'Student Attendance', 'verbose_name_plural': 'Student Attendances'},
        ),
        migrations.AddField(
            model_name='subjectnamenewmodel',
            name='class_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
