# Generated by Django 4.1.6 on 2023-06-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0110_alter_studentattendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectnamenewmodel',
            name='class_is_active',
        ),
    ]
