# Generated by Django 4.1.6 on 2023-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0111_remove_subjectnamenewmodel_class_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
    ]
