# Generated by Django 4.1.6 on 2023-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0116_attendanceqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
