# Generated by Django 4.1.6 on 2023-06-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0117_studentattendance_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.semesternewmodel'),
        ),
    ]
