# Generated by Django 4.1.6 on 2023-06-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0118_studentattendance_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.teachernamenewmodel'),
        ),
    ]
