# Generated by Django 4.1.6 on 2023-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0120_semestermodel_created_at_semestermodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnewmodel',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
