# Generated by Django 4.1.6 on 2023-07-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0123_alter_teachernamenewmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnamenewmodel',
            name='quarteirao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teachernamenewmodel',
            name='quarteirao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
