# Generated by Django 4.1.6 on 2023-07-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0124_studentnamenewmodel_quarteirao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachernamenewmodel',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
