# Generated by Django 4.1.6 on 2023-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0125_rename_image_teachernamenewmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernamenewmodel',
            name='profile_pic',
            field=models.ImageField(default='/media/profile_image2.jpg', upload_to='profiles/%y/%m/%d'),
        ),
    ]
