# Generated by Django 4.1.6 on 2023-07-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0130_teachernamenewmodel_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachernamenewmodel',
            name='profile_pic',
        ),
    ]
