# Generated by Django 4.1.6 on 2023-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0134_teachernamenewmodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnamenewmodel',
            name='profile_pic',
            field=models.ImageField(default='/media/profile_image2_removebg.png', upload_to='profiles/%Y/%m/%d'),
        ),
    ]
