# Generated by Django 4.1.6 on 2023-07-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0135_studentnamenewmodel_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAndStudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.studentnamenewmodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.teachernamenewmodel')),
            ],
        ),
    ]
