# Generated by Django 4.1.6 on 2023-07-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0136_teacherandstudentmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherandstudentmessage',
            old_name='updated_at',
            new_name='rese_at',
        ),
        migrations.RenameField(
            model_name='teacherandstudentmessage',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
