# Generated by Django 4.1.6 on 2023-07-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0137_rename_updated_at_teacherandstudentmessage_rese_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherandstudentmessage',
            old_name='rese_at',
            new_name='resent_at',
        ),
    ]
