# Generated by Django 4.1.6 on 2023-07-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0138_rename_rese_at_teacherandstudentmessage_resent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherandstudentmessage',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Message (Teacher <> Student)', 'verbose_name_plural': 'Messages (Teacher <> Student)'},
        ),
    ]
