# Generated by Django 4.1.6 on 2023-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0139_alter_teacherandstudentmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
