# Generated by Django 4.1.6 on 2023-07-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0140_studentattendance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.turmanewmodel'),
        ),
    ]
