# Generated by Django 4.1.6 on 2023-07-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0141_studentattendance_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.classenewmodel'),
        ),
    ]
