# Generated by Django 4.1.6 on 2023-07-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0143_studentattendance_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('day', models.CharField(choices=[('2ª Feira', '2ª Feira'), ('3ª Feira', '3ª Feira'), ('4ª Feira', '4ª Feira'), ('5ª Feira', '5ª Feira'), ('6ª Feira', '6ª Feira')], default='2ª Feira', max_length=8)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.subjectnamenewmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(blank=True, to='app2.timetableday')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.semestermodel')),
            ],
        ),
    ]
